'''
Created on Aug 23, 2014

@author: paulie
'''

EVE_ACTIVITY_MANUFACTURING = 1
EVE_ACTIVITY_RESEARCH_TE = 3
EVE_ACTIVITY_RESEARCH_ME = 4
EVE_ACTIVITY_COPYING = 5
EVE_ACTIVITY_REVERSE_ENGINEERING = 7
EVE_ACTIVITY_INVENTION = 8

FACILITY_ME_BONUS_POS_ASSEMBLY_ARRAY = 2
FACILITY_ME_BONUS_POS_THUKKER_ARRAY = 10
FACILITY_ME_BONUS_OUTPOST = 0

if __name__ == '__main__':
    pass